-- FastOrder: Dynamic Service Fee Configuration Table
-- Migration: 0009_add_service_fee_configs.sql

CREATE TABLE IF NOT EXISTS service_fee_configs (
  id TEXT PRIMARY KEY DEFAULT 'default',
  is_enabled BOOLEAN NOT NULL DEFAULT true,
  tier1_max_egp INTEGER NOT NULL DEFAULT 100,
  tier1_fee_cash INTEGER NOT NULL DEFAULT 3,
  tier1_fee_online INTEGER NOT NULL DEFAULT 2,
  tier2_max_egp INTEGER NOT NULL DEFAULT 200,
  tier2_fee_cash INTEGER NOT NULL DEFAULT 5,
  tier2_fee_online INTEGER NOT NULL DEFAULT 4,
  tier3_fee_cash INTEGER NOT NULL DEFAULT 10,
  tier3_fee_online INTEGER NOT NULL DEFAULT 8,
  free_days_of_week JSONB NOT NULL DEFAULT '[]'::jsonb,
  special_free_date TEXT,
  free_day_banner_text TEXT NOT NULL DEFAULT '🎉 اليوم طلبك بدون أي رسوم خدمة في الحرم الجامعي!',
  first_order_free BOOLEAN NOT NULL DEFAULT true,
  min_fee_cap INTEGER NOT NULL DEFAULT 0,
  max_fee_cap INTEGER NOT NULL DEFAULT 15,
  promo_discount_percent INTEGER NOT NULL DEFAULT 0,
  promo_discount_active BOOLEAN NOT NULL DEFAULT false,
  promo_discount_ends_at TIMESTAMPTZ,
  promo_banner_text TEXT DEFAULT '🔥 خصم خاص على رسوم الخدمة لفترة محدودة!',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by TEXT DEFAULT 'مدير النظام'
);

-- Seed initial row
INSERT INTO service_fee_configs (
  id,
  is_enabled,
  tier1_max_egp,
  tier1_fee_cash,
  tier1_fee_online,
  tier2_max_egp,
  tier2_fee_cash,
  tier2_fee_online,
  tier3_fee_cash,
  tier3_fee_online,
  free_days_of_week,
  special_free_date,
  free_day_banner_text,
  first_order_free,
  min_fee_cap,
  max_fee_cap,
  promo_discount_percent,
  promo_discount_active,
  promo_discount_ends_at,
  promo_banner_text,
  updated_by
) VALUES (
  'default',
  true,
  100,
  3,
  2,
  200,
  5,
  4,
  10,
  8,
  '[]'::jsonb,
  NULL,
  '🎉 اليوم طلبك بدون أي رسوم خدمة في الحرم الجامعي!',
  true,
  0,
  15,
  0,
  false,
  NULL,
  '🔥 خصم خاص على رسوم الخدمة لفترة محدودة!',
  'مدير النظام'
) ON CONFLICT (id) DO NOTHING;
